USE [CRDM]
GO

/****** Object:  Table [dbo].[PersonFileMap]    Script Date: 9/10/2016 1:37:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PersonFileMap](
	[PersonFileID] [uniqueidentifier] NOT NULL,
	[PersonID] [int] NOT NULL,
 CONSTRAINT [PK_PersonFileMap] PRIMARY KEY CLUSTERED 
(
	[PersonFileID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


